apiVersion: operator.openshift.io/v1
kind: OLM
metadata:
  name: cluster
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"
    capability.openshift.io/name: "OperatorLifecycleManagerV1"
    release.openshift.io/create-only: "true"
spec:
  managementState: Managed
  logLevel: Debug
  operatorLogLevel: Normal
